<div class="page-header">
    <h1>
        Edición del Usuario
        <small><?php eh(strtoupper($usuario->login)) ?></small>
    </h1>
</div>
<?php View::content() ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('usuario.id') ?>
<div class="clearfix">
    <label for="usuario_roles_id">Rol del Usuario* : </label>   
    <?php echo Form::dbSelect('usuario.roles_id', 'rol') ?>
</div>
<div class="clearfix">
    <label for="usuario_activo">Activo : </label>
    <?php echo Form::select('usuario.activo', array('1' => 'Si', '0' => 'No')) ?>
</div>
<div class="actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn primary"') ?>
    <?php echo Html::linkAction('','Cancelar','class="btn"') ?>
</div>
<?php echo Form::close() ?>
