<div id="scaffold_form">
    <h1>Configuraci&oacute;n de Perfil</h1>
    <div id="mensajes_flash" >        
        <?php View::content() ?>
    </div>
    <fieldset>
        <legend>Configurar Datos Personales</legend>
        <?php echo Form::open() ?>
        <table>
            <tr>
                <td><label for="usuario_login">Nombre de Usuario : </label></td>
                <td><b><?php eh(strtoupper($usuario1->login)) ?></b></td>
            </tr>
            <tr>
                <td><label for="usuario_nombres">Nombre Completo* : </label></td>
                <td><?php echo Form::text('usuario1.nombres') ?></td>
            </tr>
            <tr>
                <td><label for="usuario_email">Correo Electronico* : </label></td>
                <td><?php echo Form::text('usuario1.email') ?></td>
            </tr>
        </table>
        <div class="actions">
            <?php echo Form::submit('Guardar Cambios', 'name="datos_personas"') ?>
        </div>
        <?php echo Form::close() ?>
        </fieldset>
        <br/>
        <fieldset>
            <legend>Cambiar Contrase&ntilde;a</legend>
        <?php echo Form::open() ?>
            <table>
                <tr>
                    <td><label for="usuario_clave">Contrase&ntilde;a Actual * : </label></td>
                    <td><?php echo Form::pass('usuario2.clave_actual') ?></td>
                </tr>
                <tr>
                    <td><label for="usuario_clave">Nueva Contrase&ntilde;a* : </label></td>
                    <td><?php echo Form::pass('usuario2.nueva_clave') ?></td>
                </tr>
                <tr>
                    <td><label for="usuario_clave2">Volver a escribir Contrase&ntilde;a* : </label></td>
                    <td><?php echo Form::pass('usuario2.nueva_clave2') ?></td>
                </tr>
            </table>
            <div class="actions">
            <?php echo Form::submit('Guardar Cambios', 'name="cambiar_clave"') ?>
        </div>
        <?php echo Form::close() ?>
    </fieldset>
</div>
