<div id="form_logueo">
    <h3>Iniciar Sesi&oacute;n</h3>
    <?php View::content() ?>
    <?php echo Form::open() ?>
    <table>
        <tr>
            <td><label for="login">Usuario </label></td>
            <td><?php echo Form::text('login') ?></td>
        </tr>
        <tr>
            <td><label for="clave">Contrase&ntilde;a </label></td>
            <td><?php echo Form::pass('clave') ?></td>
        </tr>
        <tr>
            <td></td>
            <td><?php echo Form::submit('Ingresar') ?></td>
        </tr>
    </table>
    <?php echo Form::close() ?>
</div>