<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <title><?php echo Config::get('config.application.name') ?></title>
        <?php View::partial('css') ?>
        <?php View::partial('js') ?>
    </head>
    <body>
        <?php View::partial('cabecera_admin') ?>        
        <div class="container">
            <div id="contenido" class="content">
                <?php View::content(); ?>
            </div>
            <?php View::partial('pie') ?>   
        </div>
    </body>
</html>
