<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset=<?php echo APP_CHARSET ?>' />
        <title><?php echo Config::get('config.application.name') ?></title>
        <?php View::partial('css') ?>
        <?php View::partial('js') ?>
    </head>
    <body>
        <div id='cabecera' class="topbar">
            <div class="fill">
                <div class="container">
                    <h3><a>Modulo de Administracion</a></h3>
                    <?php View::renderMenu() ?>
                </div>
            </div>
        </div>
        <div id="contenido" class="content">
            <?php View::content(); ?>
        </div>
        <footer>
            <p>
                <?php echo 'Tiempo: ' . round((microtime(1) - START_TIME), 4) . ' seg.';
                echo ', Memoria Usada: ' . number_format(memory_get_usage() / 1048576, 2) . ' MB'; ?>
            </p>
        </footer>
    </body>
</html>
