<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <title><?php echo Config::get('config.application.name') ?></title>
        <?php View::partial('css') ?>
        <?php View::partial('js') ?>
    </head>
    <body>
        <?php View::partial('cabecera_app') ?>   
        <div class="container">
            <div id="contenido" class="content">
                <div id="form_logueo" class="form-stacked">
                    <h3>Iniciar Sesi&oacute;n</h3>
                    <?php View::content() ?>
                    <?php echo Form::open() ?>
                    <div class="clearfix">
                        <label for="login">Usuario </label>
                        <?php echo Form::text('login') ?>
                    </div>
                    <div class="clearfix">
                        <label for="clave">Contrase&ntilde;a </label>
                        <?php echo Form::pass('clave') ?>
                    </div>
                    <div class="submit_logueo">
                        <?php echo Form::submit('Ingresar','class="btn primary"') ?>
                    </div>
                    <?php echo Form::close() ?>
                </div>
            </div>
            <footer>
                <p>
                    <?php echo 'Tiempo: ' . round((microtime(1) - START_TIME), 4) . ' seg.';
                    echo ', Memoria Usada: ' . number_format(memory_get_usage() / 1048576, 2) . ' MB'; ?>
                </p>
            </footer>
        </div>
    </body>
</html>
