<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<?php View::content() ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('rol.id') ?>
<div class="clearfix">
    <label for="rol_rol">Nombre del rol* : </label>
    <?php echo Form::text('rol.rol') ?>            
</div>
<div class="clearfix">
    <label for="rol_plantilla">Plantilla a Usar : </label>
    <?php echo Form::text('rol.plantilla') ?>            
</div>
<div class="clearfix" id="select_padres">
    <label for="menu2.roles_id">Padres del rol : </label>
    <?php echo Form::dbSelect('menu2.roles_id', 'rol') ?>
</div>
<div id="roles_padres" class="clearfix">
</div>
<div class="clearfix">
    <label for="menus_activo">Activo (Visible) : </label>
    <?php echo Form::select('menus.activo', array('1' => 'Si', '0' => 'No')) ?>            
</div>
<div class="actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn primary"') ?>
    <?php echo Html::linkAction('','Cancelar','class="btn"') ?>
</div>
<?php echo Form::close() ?>
<script type="text/javascript">
    $(function(){
        var url = <?php echo PUBLIC_PATH ?> + "admin/roles/agregar_padre/";
        $("#select_padres select").live('change',function(){
            var padre = $('option:selected',this).text();
            if ( $("#roles_padres").html().indexOf(padre) < 0 &&
                $('option:selected',this).val() != "<?php @eh($rol->id) ?>" ) {
                $.post(url + $('option:selected',this).val(),{},function(data){
                    $("#roles_padres").append(data);
                });
            }
        });
        
        $("#roles_padres .rol_padre span").live('click',function(){
            $(this).parent().remove();
        });
<?php if (isset($rol) and $rol->padres) : ?>
    <?php foreach (explode(',', $rol->padres) as $e) : ?>
                    $.post(url + <?php eh($e) ?>,{},function(data){
                        $("#roles_padres").append(data);                
                    });
    <?php endforeach ?>
<?php endif ?>
    });
</script>              
