<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<?php View::content() ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('recurso.id') ?>
<div class="row clearfix">
    <div class="span-one-third">
        <label for="recurso_modulo">Modulo : </label>
    </div>
    <div class="span-one-third">
        <label for="recurso_controlador">Controlador * :</label>
    </div>
    <div class="span-one-third">
        <label for="recurso_accion">Accion  : </label>
    </div>
</div>
<div class="row clearfix">
    <div class="span-one-third">
        <?php echo Form::text('recurso.modulo', 'class="span5"') ?>
    </div>
    <div class="span-one-third">
        <?php echo Form::text('recurso.controlador', 'class="span5"') ?>
    </div>
    <div class="span-one-third">
        <?php echo Form::text('recurso.accion', 'class="span5"') ?>
    </div>
</div>
<div class="clearfix">
    <label for="recurso_descripcion">Descripcion * : </label>
    <?php echo Form::textarea('recurso.descripcion', 'class="span8"') ?>            
</div>
<div class="clearfix">
    <label for="menus_activo">Activo (Visible) : </label>
    <?php echo Form::select('menus.activo', array('1' => 'Si', '0' => 'No')) ?>            
</div>
<div class="actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn primary"') ?>
    <?php echo Html::linkAction('','Cancelar','class="btn"') ?>
</div>
<?php echo Form::close() ?>