<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<?php View::content() ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('recurso.id') ?>
<div class="row">
    <div class="span-one-third">
        <label for="recurso_modulo">Modulo : </label>
    </div>
    <div class="span-one-third">
        <label for="recurso_controlador">Controlador * :</label>
    </div>
    <div class="span-one-third">
        <label for="recurso_accion">Accion  : </label>
    </div>
</div>
<div class="row">
    <div class="span-one-third">
        <?php echo Form::text('recurso.modulo', 'class="span5"') ?>
    </div>
    <div class="span-one-third">
        <?php echo Form::text('recurso.controlador', 'class="span5"') ?>
    </div>
    <div class="span-one-third">
        <?php echo Form::text('recurso.accion', 'class="span5"') ?>
    </div>
</div>
<div class="clearfix">
        <label for="recurso_descripcion">Descripcion * : </label>
        <?php echo Form::textarea('recurso.descripcion') ?>            
</div>
<div class="clearfix">
        <label for="menus_activo">Activo (Visible) : </label>
        <?php echo Form::select('menus.activo', array('1' => 'Si', '0' => 'No')) ?>            
</div>
<div class="actions">
    <?php echo Form::submit('Guardar Datos') ?>
    <?php echo Form::submit('Cancelar', 'name="cancelar"') ?>
</div>
<?php echo Form::close() ?>
<style type="text/css">
    .input_pequenios input{
        width: 150px !important;
    }
</style>