<div id="scaffold_form">
    <h1><?php eh($titulo) ?></h1>
    <div id="mensajes_flash" >        
        <?php View::content() ?>
    </div>
    <?php echo Form::open() ?>
    <?php echo Form::hidden('menu.id') ?>
        <table>
            <tr>
                <td><label for="menu_menu_id">Menu Padre : </label></td>
                <td><?php echo Form::dbSelect('menu.menus_id', 'nombre', array('menus','find','activo = "1"'), 'Ninguno') ?></td>
            </tr>
            <tr>
                <td><label for="menu_recursos_id">Recurso al que Accede : </label></td>
                <td><?php echo Form::dbSelect('menu.recursos_id', 'recurso') ?></td>
            </tr>
            <tr>
                <td><label for="menu_nombre">Texto a Mostrar : </label></td>
                <td><?php echo Form::text('menu.nombre') ?></td>
            </tr>
            <tr>
                <td><label for="menu_url">Url del Menu : </label></td>
                <td><?php echo Form::text('menu.url') ?></td>
            </tr>
            <tr>
                <td><label for="menu_posicion">Posicion en el Menu : </label></td>
                <td><?php echo Form::text('menu.posicion') ?></td>
            </tr>
            <tr>
                <td><label for="menu_clases">Clases del Menu : </label></td>
                <td><?php echo Form::text('menu.clases') ?></td>
            </tr>
            <tr>
                <td><label for="menu_activo">Activo (Visible) : </label></td>
                <td><?php echo Form::select('menu.activo', array('1' => 'Si', '0' => 'No')) ?></td>
            </tr>
        </table>
        <div class="actions">
        <?php echo Form::submit('Guardar') ?>
        <?php echo Form::submit('Cancelar', 'name="cancelar"') ?>
    </div>
    <?php echo Form::close() ?>
</div>
<script type="text/javascript" >
    $(function(){
        $("#menu_recursos_id").live('change',function(){
            var recurso = $('option:selected',this).text();
            $("#menu_url").val(recurso.replace('/*',''));
        });
    });
</script>