<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<?php View::content() ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('menu.id') ?>
<div class="clearfix">
    <label for="menu_menu_id">Menu Padre : </label>
    <?php echo Form::dbSelect('menu.menus_id', 'nombre', array('menus', 'find', 'activo = "1"'), 'Ninguno') ?>
</div>
<div class="clearfix">
    <label for="menu_recursos_id">Recurso al que Accede : </label>
    <?php echo Form::dbSelect('menu.recursos_id', 'recurso') ?>
</div>
<div class="clearfix">
    <label for="menu_nombre">Texto a Mostrar : </label>
    <?php echo Form::text('menu.nombre') ?>
</div>
<div class="clearfix">
    <label for="menu_url">Url del Menu : </label>
    <?php echo Form::text('menu.url') ?>
</div>
<div class="clearfix">
    <label for="menu_posicion">Posicion en el Menu : </label>
    <?php echo Form::text('menu.posicion') ?>
</div>
<div class="clearfix">
    <label for="menu_clases">Clases del Menu : </label>
    <?php echo Form::text('menu.clases') ?>
</div>
<div class="clearfix">
    <label for="menu_activo">Activo (Visible) : </label>
    <?php echo Form::select('menu.activo', array('1' => 'Si', '0' => 'No')) ?>
</div>
<div class="actions">
    <?php echo Form::submit('Guardar', 'class="btn primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
</div>
<?php echo Form::close() ?>
<script type="text/javascript" >
    $(function(){
        $("#menu_recursos_id").live('change',function(){
            var recurso = $('option:selected',this).text();
            $("#menu_url").val(recurso.replace('/*',''));
        });
    });
</script>