<div id="form_logueo">
    <?php View::content() ?>
    <?php echo Form::open() ?>
    <table>
        <tr>
            <td><label for="login">Login : </label></td>
            <td><?php echo Form::text('login') ?></td>
        </tr>
        <tr>
            <td><label for="clave">Clave : </label></td>
            <td><?php echo Form::text('clave') ?></td>
        </tr>
        <tr>
            <td></td>
            <td><?php echo Form::submit('Ingresar') ?></td>
        </tr>
    </table>
    <?php echo Form::close() ?>
</div>